---
title       : Twin Cities, Minnesota Demographics
subtitle    : Exploration of Race, Income, Age by Zip Code
author      : Bill Rowe
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : default      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

 

## Twin Cities, MN Metropolitan Statistical Area

This Shiny app uses choropleth maps to explore the demographics of the Twin Cities Metropolitan Statistical Area.  The Twin Cities MSA that includes 10 counties in Minnesota and 2 counties in western Wisconsin (separated by the St. Croix River). A choropleth map (from Greek χώρο ("area/region") + πλήθος ("multitude")) is a thematic map.  Areas are colored in proportion to the value of a statistic like per-capita income or percent Hispanic as examples.

Metropolitan Statistical Areas [Metropolitan Statistical Area (MSA)](https://en.wikipedia.org/wiki/Metropolitan_statistical_area) are defined by the Census Bureau. The regions in the images are the Census Bureau's approximation ([Zip Code Tabulated Areas (ZCTAS)](https://www.census.gov/geo/reference/zctas.html)) of postal zip codes.  All the data is from the 2013 [American Community Survey (ACS)](http://www.census.gov/acs/www/) accessed via the [choropleth](https://cran.r-project.org/web/packages/choroplethr/choroplethr.pdf) package created by [Ari Lamestein](http://www.arilamstein.com/).

--- .class #id 

 

## How to Use the Maps Tab


The ***Maps*** tab shows the distribution of a demographic statistic across the statistical area. The drop down can be used to chose the demographic that will be presented on a map of the Twin Cities MSA.  The following map shows the distribution of African Americans across the Twin Cities by Zip Code.



---

 

## How to Use the Plots Tab

The ***Plots*** tab creates scatter plots of the demographics versus other other selected demographics.  The following is a plot of the fraction of white residents vs the fraction of black residents.  This seems to mirror the
---

## Maps

The following maps imply that the Twin Cities MSA is an example of geographical segregation.  The African American population seems  to cluster in the ZCTAs in the center of the city, and the White population seems to cluter in the ZCTAs outside the center of the city.  This is also true for the hispanic and asian populationns (mostly Hmong and Vietnamese).

---

## Slide 5

The R code (server.R, ui.R and Top.md) for this app can be found on [GitHub](https://github.com/wer61537/shiny_app).

---

 
